(()=>{
const stories={
dungeon:{tab:'Find your party',title:'Your next party could be standing beside you.',alt:'A human paladin with a shield meets a night elf druid healer at the Deadmines mine entrance.',left:{viewer:'Selene’s view · hovering Aldric',name:'Aldric Dawnshield',native:'Human Paladin · Friendly traveler',label:'Wayfarer · A shared road',lines:['Tank · Looking for a healer','Deadmines · shared plan'],match:'You offered healing for this run'},right:{viewer:'Aldric’s view · hovering Selene',name:'Selene Moonbough',native:'Night Elf Druid · Friendly traveler',label:'Wayfarer · They can help you',lines:['Healer · Looking for a dungeon run','Deadmines · shared plan'],match:'Matches the healer role you requested'},toast:{category:'ROAD · PROPOSED QUIET CUE',title:'A shared road',text:'You both chose Deadmines. There may be a reason to say hello.'},notes:[['A tank with a plan','Aldric deliberately shares Tank, Deadmines and Looking for a healer. Selene sees that plan when she hovers him.'],['A healer going the same way','Selene shares Healer and the same dungeon. Aldric’s tooltip makes the connection clear. Both choose whether to chat or group.'],['A nudge, when welcome','A restrained Road cue can invite a closer look. It is a proposed presentation, governed by your notification settings and the shared attention budget.']]},
loan:{tab:'Remember a favor',title:'The Tome remembers the kindness between you.',alt:'A dwarf shaman offers a coin purse to a human paladin inside the warm stone halls of Ironforge.',left:{viewer:'Thorin’s view · hovering Aldric',name:'Aldric Dawnshield',native:'Human Paladin · Remembered companion',label:'Wayfarer · Private reminder',lines:['Loaned Aldric 10 gold','10 gold remains open','Acknowledged by both of you'],match:'Private reminder text · opted in'},right:{viewer:'Aldric’s view · hovering Thorin',name:'Thorin Emberhand',native:'Dwarf Shaman · Remembered companion',label:'Wayfarer · Your private reminder',lines:['You owe Thorin 10 gold','Acknowledged loan · still open'],match:'Private reminder text · opted in'},toast:{category:'MEMORY · PROPOSED QUIET CUE',title:'A promise remembered',text:'A record with Aldric is ready to review in your Tome.'},notes:[['A favor you both recognize','The example starts after both players acknowledge the 10-gold loan. The amount is player-confirmed, not a claim of automatic trade tracking.'],['Your reminder stays yours','These are two separate private views. Reminder text needs an explicit local tooltip opt-in; notes are hidden by default. Other players cannot see this debt.'],['Review it in People','Open Promises to review or propose repayment, forgiveness or another change. Changes to the shared record need acknowledgment; the addon never collects payment.']]},
materials:{tab:'Connect your crafts',title:'Someone nearby has the missing piece.',alt:'A human leatherworker offers a roll of heavy leather to a night elf druid at a Darnassus crafting bench.',left:{viewer:'Selene’s view · hovering Mira',name:'Mira Greythorne',native:'Human Leatherworker · Friendly traveler',label:'Wayfarer · They can help you',lines:['Heavy Leather marked available','Your Blueprint needs 3 Heavy Leather'],match:'An offer matches your private goal'},right:{viewer:'Mira’s view · hovering Selene',name:'Selene Moonbough',native:'Night Elf Druid · Friendly traveler',label:'Wayfarer · You can help them',lines:['Looking for Heavy Leather','Selected material need · shared'],match:'You marked Heavy Leather available'},toast:{category:'CRAFT · PROPOSED QUIET CUE',title:'A crafting connection',text:'An eligible Heavy Leather offer matches the goal you pinned.'},notes:[['They have what you need','Selene’s private Blueprint can match Mira’s explicitly shared offer. Owning leather alone never tells other players it is available.'],['You choose what they see','Mira sees the reciprocal need here because Selene also chose to share it. If Selene keeps her goal private, that need is not sent to Mira.'],['Start the conversation yourself','Open the connection and review an Ask About This draft. You decide whether to send it, negotiate or trade; no message or trade is automatic.']]}
};
stories.alignment={tab:'Nearby alignment',title:'Your paths can cross before you say a word.',alt:'A druid’s subtle blue and gold ping reaches a nearby paladin and dwarf at the Deadmines mine entrance.',notes:[['A gentle nearby ping','With nearby discovery and sharing enabled, your Wayfarer checks for participating travelers around you. The rings illustrate the ping; they are not a permanent effect on the world.'],['Plans, goals, needs and activities align','A shared Deadmines plan links healer and tank. A Heavy Leather offer matches your pinned crafting need. Matches use eligible shared choices; private goals stay local.'],['A toast reveals the connection','A small ping and a concise toast tell you why this traveler matters now. Open the connection when you want, then choose whether to talk, group or trade.']]};
function alignmentScene(s){return '<div class="connection-image alignment-scene"><img src="assets/comic/alignment.png" alt="'+s.alt+'"><div class="alignment-choices"><span class="connection-number">1</span><small>YOUR CHOSEN ROAD</small><h3>Selene Moonbough</h3><p>Healer · Deadmines</p><p>Crafting goal · Leather bracers</p><p>Need · 3 Heavy Leather</p><span>Nearby discovery enabled</span></div><div class="connection-toast alignment-toast"><span class="connection-number">3</span><small>WAYFARER · NEARBY ALIGNMENT</small><svg class="alignment-bell" viewBox="0 0 24 24" role="img" aria-label="Gentle ping"><path d="M5 17h14l-2-3V9a5 5 0 0 0-10 0v5zM10 20h4" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"/></svg><h3>Your roads align</h3><p><strong>Aldric Dawnshield</strong><br>Tank · Deadmines<br>Looking for a healer</p><p><strong>Thorin Emberhand</strong><br>Heavy Leather marked available<br>Matches your crafting goal</p><div class="alignment-open">View connections →</div></div><div class="alignment-cue"><span class="connection-number">2</span> A shared road. A matching need.</div><span class="connection-stamp">WAYFARER · INTENDED DESIGN · NEARBY ALIGNMENT</span></div>';}
stories.pvp={tab:'Remember your rivals',title:'Some names are remembered on the other side of the road.',alt:'A night elf druid in bear form faces an orc affliction warlock on a contested Ashenvale woodland road.',left:{viewer:'Gorhazak’s view · hovering Vaelthorn',name:'Vaelthorn',native:'Night Elf Druid · Enemy player',label:'Wayfarer · An old adversary',lines:['You have slain Vaelthorn:','Open-world PvP · 2 times','Battlegrounds · 4 times'],match:'They have felled you · 12 times'},right:{viewer:'Vaelthorn’s view · hovering Gorhazak',name:'Gorhazak',native:'Orc Warlock · Enemy player',label:'Wayfarer · An old adversary',lines:['You have slain Gorhazak:','Open-world PvP · 4 times','Battlegrounds · 8 times'],match:'They have felled you · 6 times'},notes:[['A name with a history','Hover a remembered opponent before combat to see your supported, credited defeats and deaths. Battleground counts refer to this rival, not your team’s match wins.'],['Your own past results','This sample history against Gorhazak has 8 wins / 2 losses in Restoration and 4 / 4 in Feral: an 80% versus 50% recorded win share. It describes remembered encounters, not the cause of those outcomes.'],['The world keeps your attention','The detailed preview is out of combat. During combat, the tooltip contracts to a brief recognition cue. Full rivalry history and your own past spec context remain in the Tome.']]};
function pvpScene(s){return '<div class="connection-image pvp-scene"><img src="assets/comic/pvp.png" alt="'+s.alt+'">'+tip(s.left,'left',1)+tip(s.right,'right',2)+'<svg class="connection-cursor pvp-cursor" viewBox="0 0 30 40" aria-hidden="true"><path d="M3 2v30l7-7 6 12 6-3-6-12h11z" fill="#fff7df" stroke="#071929" stroke-width="2"/></svg><div class="connection-toast pvp-history"><span class="connection-number">3</span><small>YOUR TOME · PAST RESULTS AGAINST GORHAZAK</small><h3>A rivalry across your roles</h3><p>Restoration · 8 wins / 2 losses <strong>80%</strong></p><p>Feral · 4 wins / 4 losses <strong>50%</strong></p><p class="pvp-summary">Your recorded win share was higher in Restoration.</p><div class="alignment-open">Open rivalry history →</div></div><span class="connection-stamp">DETAILED · BEFORE COMBAT · FICTIONAL HISTORY</span></div>';}
const cursor='<svg class="connection-cursor SIDE" viewBox="0 0 30 40" aria-hidden="true"><path d="M3 2v30l7-7 6 12 6-3-6-12h11z" fill="#fff7df" stroke="#071929" stroke-width="2"/></svg>';
const nativePlayers={
'Aldric Dawnshield':'THE WAYWARD COMPANY\nLevel 22 Human (Player)\nPaladin\nAlliance\nPvP',
'Selene Moonbough':'THE WAYWARD COMPANY\nLevel 22 Night Elf (Player)\nDruid\nAlliance\nPvP',
'Thorin Emberhand':'THE WAYWARD COMPANY\nLevel 22 Dwarf (Player)\nShaman\nAlliance\nPvP',
'Mira Greythorne':'THE WAYWARD COMPANY\nLevel 22 Human (Player)\nHunter\nAlliance\nPvP',
'Vaelthorn':'MOONWARDENS\nLevel 40 Night Elf (Player)\nDruid\nAlliance\nPvP',
'Gorhazak':'THE ASHEN OATH\nLevel 40 Orc (Player)\nWarlock\nHorde\nPvP'};
function tip(data,side,n){return '<div class="connection-tip '+side+'"><span class="connection-number">'+n+'</span><div class="perspective">'+data.viewer+'</div><h3>'+data.name+'</h3><p class="native">'+(nativePlayers[data.name]||data.native)+'</p><p class="wayfarer-label">'+data.label+'</p><ul>'+data.lines.map(line=>'<li>'+line+'</li>').join('')+'<li class="match">'+data.match+'</li></ul><p class="tome-hint">Open in Forever Tome →</p></div>'}
for(const host of document.querySelectorAll('.connections-demo')){
host.innerHTML='<div class="eyebrow">The Tome is useful while closed</div><h2>A reason to say hello.</h2><p class="intro">A gentle nearby ping can reveal an aligned plan, goal, need or activity. A toast tells you why your roads cross; tooltips add the shared context and remembered story.</p><div class="connection-tabs" role="group" aria-label="Choose a connection story">'+Object.entries(stories).map(([id,s])=>'<button type="button" data-story="'+id+'" aria-pressed="false">'+s.tab+'</button>').join('')+'</div><div class="connection-panel" aria-live="polite"></div><p class="connection-limit">Comic intended-design examples with fictional records. Both tooltips are shown together to explain two separate player perspectives; each player normally sees one hovered subject. Optional toast examples are not alerts on every hover. Combat and busy moments defer or suppress them, and Quiet / Normal / Talkative plus category controls decide what speaks.</p><a class="connection-download" href="#">Open annotated image ↗</a>';
const show=id=>{const s=stories[id]||stories.dungeon;host.querySelector('.connection-panel').innerHTML=(id==='pvp'?pvpScene(s):id==='alignment'?alignmentScene(s):'<div class="connection-image"><img src="assets/comic/'+id+'.png" alt="'+s.alt+'">'+tip(s.left,'left',1)+tip(s.right,'right',2)+cursor.replace('SIDE','left')+cursor.replace('SIDE','right')+'<div class="connection-toast"><span class="connection-number">3</span><small>'+s.toast.category+'</small><h3>'+s.toast.title+'</h3><p>'+s.toast.text+'</p></div><span class="connection-stamp">WAYFARER · INTENDED DESIGN · TWO PLAYER PERSPECTIVES</span></div>')+'<div class="connection-caption"><h3>'+s.title+'</h3><div class="connection-notes">'+s.notes.map(([title,copy],i)=>'<p><strong><span class="connection-number">'+(i+1)+'</span>'+title+'</strong>'+copy+'</p>').join('')+'</div></div>';if(id==='loan'){host.querySelector('.connection-cursor.left').style.cssText='left:56%;top:43%';host.querySelector('.connection-cursor.right').style.cssText='left:36%;top:48%';}host.querySelectorAll('[data-story]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.story===id)));host.querySelector('.connection-limit').textContent=id==='pvp'?'Comic intended-design example with fictional history. Spec results describe your own recorded past. The warlock’s Affliction theme belongs to the illustration; no live enemy specialization, cooldown, inventory or tactical advice is exposed. Supported attribution and own-spec history require client validation.':id==='alignment'?'Comic intended-design example with fictional records. Nearby discovery concerns participating Wayfarer users and eligible sharing settings. A private goal can match a shared offer without being sent. Pings and toasts respect quiet settings, cooldowns and busy moments; nearby detection and transport remain subject to client validation.':'Comic intended-design examples with fictional records. Both tooltips show two separate player perspectives. Quiet settings and busy moments govern the optional toast examples.';host.querySelector('.connection-download').href='assets/tooltip-stories/'+id+'-annotated.png';};
host.querySelectorAll('[data-story]').forEach(b=>b.addEventListener('click',()=>show(b.dataset.story)));
const params=new URLSearchParams(location.search);const requested=params.get('story');if(params.has('capture'))host.classList.add('connection-single');show(stories[requested]?requested:'alignment');
}
})();
